fs_logger("notice","[dialplan/custom_dialplan.lua][XML_STRING] IN playback");
hangup_cause = "NORMAL_CLEARING";

xml = {};
table.insert(xml, [[<?xml version="1.0" encoding="UTF-8" standalone="no"?>]]);
table.insert(xml, [[<document type="freeswitch/xml">]]);
table.insert(xml, [[<section name="dialplan" description="CCPBX Dialplan">]]);
table.insert(xml, [[<context name="default">]]);
table.insert(xml, [[<extension name="]]..destination_number..[[">]]);
table.insert(xml, [[<condition field="destination_number" expression="92123456789">]]);
table.insert(xml, [[<action application="set" data="effective_destination_number=921234567"/>]]);
table.insert(xml, [[<action application="set" data="custom_destination_number=921234567"/>]]);
table.insert(xml, [[<action application="set" data="sticky_agent_flag=1"/>]]);
table.insert(xml, [[<action application="export" data="original_destination_number=]]..destination_number..[["/>]]);
table.insert(xml, [[<action application="set" data="authentication_type=acl"/>]]);
table.insert(xml, [[<action application="set" data="custom_callstart=2023-12-05 06:38:06"/>]]);
table.insert(xml, [[<action application="set" data="tenant_uuid=f7915448-43ee-4fb3-8c6d-f09363cea7e0"/>]]);
table.insert(xml, [[<action application="set" data="ip_map_uuid=7b3aa61a-a176-42a4-a84e-d68c49c00b1f"/>]]);
table.insert(xml, [[<action application="set" data="ringback=%(2000,4000,440,480)"/>]]);
table.insert(xml, [[<action application="export" data="custom_callid=1-1648902@5.75.226.233"/>]]);
table.insert(xml, [[<action application="export" data="sip_h_X-a_leg_call_uuid=54a1a873-ae60-4b60-8ae4-8c8b743d435e"/>]]);
table.insert(xml, [[<action application="export" data="sip_h_X-custom_callid=1-1648902@5.75.226.233"/>]]);
table.insert(xml, [[<action application="set" data="sip_h_X-custom_callid=1-1648902@5.75.226.233"/>]]);
table.insert(xml, [[<action application="export" data="sip_bye_h_custom_callid=1-1648902@5.75.226.233"/>]]);
table.insert(xml, [[<action application="set" data="sip_user=sipp"/>]]);
table.insert(xml, [[<action application="set" data="hangup_after_bridge=true"/>]]);
table.insert(xml, [[<action application="set" data="continue_on_fail=TRUE"/>]]);
table.insert(xml, [[<action application="set" data="call_type=did"/>]]);
table.insert(xml, [[<action application="export" data="presence_data=tenant_uuid=f7915448-43ee-4fb3-8c6d-f09363cea7e0,tenant=harsh,trunk=lab,user=-"/>]]);
table.insert(xml, [[<action application="set" data="original_did_number=]]..destination_number..[["/>]]);
table.insert(xml, [[<action application="set" data="hold_music=call-queue.wav"/>]]);
table.insert(xml, [[<action application="bridge_export" data="hold_music=call-queue.wav"/>]]);
table.insert(xml, [[<action application="set" data="custom_recording=0"/>]]);
table.insert(xml, [[<action application="set" data="execute_on_answer=record_session $${recordings_dir}/]]..destination_number..[[_${uuid}.wav"/>]]);
table.insert(xml, [[<action application="set" data="webphonetransfer=0"/>]]);
table.insert(xml, [[<action application="bind_meta_app" data="1 b s execute_extension::attended_xfer XML features"/>)]]);
table.insert(xml, [[<action application="bind_meta_app" data="2 a s execute_extension::attended_xfer XML features"/>)]]);
table.insert(xml, [[<action application="set" data="effective_caller_id_name=sipp"/>]]);
table.insert(xml, [[<action application="set" data="effective_caller_id_number=sipp"/>]]);
table.insert(xml, [[<action application="set" data="hangup_after_bridge=true"/>]]);
table.insert(xml, [[<action application="set" data="continue_on_fail=TRUE"/>]]);
table.insert(xml, [[<action application="set" data="did_pstn=0"/>]]);
table.insert(xml, [[<action application="bridge" data="[leg_timeout=30]sofia/gateway/lab/]]..destination_number..[["/>]]);
table.insert(xml, [[</condition>]]);
table.insert(xml, [[</extension>]]);
table.insert(xml, [[</context>]]);
table.insert(xml, [[</section>]]);
table.insert(xml, [[</document>]]);        XML_STRING = table.concat(xml, "\n");
	fs_logger("info","Generated XML:\n" .. XML_STRING)

